#://www.vagrantup.com/docs/provisioning/ansible.html


AmountOfVM = 2
GroupVMName = "Anode"

#Ansible tower
Vagrant.configure("2") do |config|
  config.vm.box = "bertvv/CentOS72"

  config.vm.define "#{VmGroupName}Tower" do |machine|
    machine.vm.hostname = "#{VmGroupName}Tower"
    machine.vm.network "private_network", ip: "192.168.100.20"
    config.vm.provision "shell",
      inline: "systemctl restart network" #anders werkt enp0s8 niet
  end

#clients
  (1..AmountOfVM).each do |machine_id|
    config.vm.define "#{GroupVMName}#{machine_id}" do |machine|
      machine.vm.hostname = "#{GroupVMName}#{machine_id}"
      machine.vm.network "private_network", ip: "192.168.100.#{20+machine_id}"
      config.vm.provision "shell",
        inline: "systemctl restart network"
      config.vm.provision "shell",
        inline: "sudo sh /vagrant/monitoring/newrelicinfra.sh"

    end
  end
end
