#://www.vagrantup.com/docs/provisioning/ansible.html


AmountOfVM = 4
GroupVMName = "Anode"

#Ansible tower
Vagrant.configure("2") do |config|


  config.vm.define "#{GroupVMName}Tower" do |machine|
    machine.vm.box = "ansible/tower"
    machine.ssh.insert_key = false
    machine.vm.hostname = "#{GroupVMName}Tower"
    machine.vm.network "private_network", ip: "192.168.100.20"
    config.vm.provision "shell",
      inline: "systemctl restart network"
  end

#clients

  (1..AmountOfVM).each do |machine_id|
      config.vm.provider "virtualbox" do |v|
          v.memory = 5000
          v.cpus = 2
      end
      config.vm.define "#{GroupVMName}#{machine_id}" do |machine|
      machine.vm.box = "centos/7"

      machine.vm.hostname = "#{GroupVMName}#{machine_id}"
      machine.vm.network "private_network", ip: "192.168.100.#{20+machine_id}"


      config.vm.provision "shell",
        inline: "systemctl restart network"
      config.vm.provision "shell",
        inline: "sudo sh /vagrant/monitoring/newrelicinfra.sh"


    end
  end
end
