AmountOfVM = 2
VmGroupName = "PPnode"
VagrantBox = "centos/7"

#Master
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
      v.memory = 5000
      v.cpus = 2
  end
    config.vm.define "#{VmGroupName}Master" do |machine|
      machine.vm.box = "#{VagrantBox}"
      machine.vm.hostname = "#{VmGroupName}Master"
      machine.vm.network "private_network", ip: "192.168.101.20"
      config.vm.provision "shell",
        inline: "systemctl restart network"
      config.vm.provision "shell",
        inline: "sudo sh /vagrant/puppetconfiguration/installpuppetserver.sh"
    end

#Clients
  (1..AmountOfVM).each do |machine_id|
    config.vm.provider "virtualbox" do |v|
        v.memory = 500
        v.cpus = 1
    end
    config.vm.define "#{VmGroupName}#{machine_id}" do |machine|
      machine.vm.box = "#{VagrantBox}"
      machine.vm.hostname = "#{VmGroupName}#{machine_id}"
      machine.vm.network "private_network", ip: "192.168.101.#{20+machine_id}"
      config.vm.provision "shell",
        inline: "systemctl restart network"
      config.vm.provision "shell",
        inline: "sudo sh /vagrant/monitoring/newrelicinfra.sh"
      config.vm.provision "shell",
        inline: "sudo sh /vagrant/puppetconfiguration/installpuppetagent.sh"
    end
  end
end
